-- 检查 User 表的当前结构
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Users';

-- 检查 Id 列是否为自增
SELECT COLUMNPROPERTY(OBJECT_ID('Users'), 'Id', 'IsIdentity') AS IsIdentity;
